apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: support
  namespace: NAMESPACE_PLACEHOLDER
rules:
- apiGroups: [""]
  resources: ["pods","pods/log","services","endpoints","configmaps","events"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments","replicasets","statefulsets"]
  verbs: ["get","list","watch"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get","list","watch"]
