apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cyber-view
  namespace: app-payments-stage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: ocp-cyber-audit
